/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day10;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LookAndSayTest {
    @Test
    void canConvert() {
        assertTrue(LookAndSay.lookAndSay("1").equals("11"));
        assertTrue(LookAndSay.lookAndSay("21").equals("1211"));
        assertTrue(LookAndSay.lookAndSay("1211").equals("111221"));
        assertTrue(LookAndSay.lookAndSay("111221").equals("312211"));
    }
}
