/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day07;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        try {
            int result = part1();
            System.out.println(String.format("a wire: %d", result));
            result = part2(result);
            System.out.println(String.format("a wire: %d", result));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static List<WireDefinition> wireDefinitions() throws Exception {
        BufferedReader br = null;
        try {
            List<WireDefinition> wds = new ArrayList<>();
            br = new BufferedReader(new FileReader("input.txt"));
            String line = br.readLine();
            while (line != null) {
                wds.add(WireDefinition.parseString(line));
                line = br.readLine();
            }
            return wds;
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }

    static int part1() throws Exception {
        List<WireDefinition> wds = wireDefinitions();
        Circuit c = new Circuit(wds.toArray(new WireDefinition[] {}));
        return c.resolveWireValue("a");
    }

    static int part2(int input) throws Exception {
        List<WireDefinition> wds = wireDefinitions();
        wds.add(WireDefinition.parseString(String.format("%d -> b", input)));
        Circuit c = new Circuit(wds.toArray(new WireDefinition[] {}));
        return c.resolveWireValue("a");
    }
}
