/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day17;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ContainerTest {
    @Test
    void canParseContainers() {
        Container[] containers = Container.parse(new String[] { "20", "15", "10", "5", "5" });

        assertEquals(containers[0], new Container(0, 20));
        assertEquals(containers[1], new Container(1, 15));
        assertEquals(containers[2], new Container(2, 10));
        assertEquals(containers[3], new Container(3, 5));
        assertEquals(containers[4], new Container(4, 5));
    }
}
