/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day16;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.HashMap;
import java.util.Map;

class SueTest {
    @Test
    void canParseString() {
        Sue sue = Sue.parseString("Sue 1: cars: 9, vizslas: 0, akitas: 0");

        Map<String, Integer> expectedMap = new HashMap<>();
        expectedMap.put("cars", 9);
        expectedMap.put("vizslas", 0);
        expectedMap.put("akitas", 0);
        Sue expected = new Sue(1, expectedMap);

        assertEquals(expected, sue);
    }
}
