/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day14;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void canParseReindeer() {
        Reindeer reindeer = Reindeer
                .parseString("Comet can fly 14 km/s for 10 seconds, but then must rest for 127 seconds.");
        Reindeer expectedReindeer = new Reindeer("Comet", 14, 10, 127);
        assertTrue(reindeer.equals(expectedReindeer));

        reindeer = Reindeer.parseString("Dancer can fly 16 km/s for 11 seconds, but then must rest for 162 seconds.");
        expectedReindeer = new Reindeer("Dancer", 16, 11, 162);
        assertTrue(reindeer.equals(expectedReindeer));
    }

    @Test
    void canCalculateReindeerDistance() {
        Reindeer comet = Reindeer
                .parseString("Comet can fly 14 km/s for 10 seconds, but then must rest for 127 seconds.");
        assertTrue(comet.distance(1) == 14);
        assertTrue(comet.distance(10) == 140);
        assertTrue(comet.distance(12) == 140);
        assertTrue(comet.distance(1000) == 1120);

        Reindeer dancer = Reindeer
                .parseString("Dancer can fly 16 km/s for 11 seconds, but then must rest for 162 seconds.");
        assertTrue(dancer.distance(1) == 16);
        assertTrue(dancer.distance(10) == 160);
        assertTrue(dancer.distance(12) == 176);
        assertTrue(dancer.distance(1000) == 1056);
    }
}
