/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day02;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void canParseGiftBox() {
        assertTrue(GiftBox.parse("2x3x4").equals(new GiftBox(2, 3, 4)));
        assertTrue(GiftBox.parse("1x1x10").equals(new GiftBox(1, 1, 10)));
    }

    @Test
    void canGetWrappingPaperRequired() {
        assertTrue(GiftBox.parse("2x3x4").wrappingPaperRequired() == 58);
        assertTrue(GiftBox.parse("1x1x10").wrappingPaperRequired() == 43);
    }

    @Test
    void canGetRibbonRequired() {
        assertTrue(GiftBox.parse("2x3x4").ribbonRequired() == 34);
        assertTrue(GiftBox.parse("1x1x10").ribbonRequired() == 14);
    }

}
