[package]
name = "part01"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
itertools = "0.11.0"
rand = "0.8.5"

[profile.release]
debug = true

[[bench]]
name = "solving_benchmark"
harness = false

