/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day18;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

class LightGridTest {
    @Test void canParseGrid() throws FileNotFoundException, IOException {
        LightGrid lightGrid = LightGrid.parse(new FileInputStream("test-input.txt"));
        String output = lightGrid.getOutput();
        assertTrue(output.equals(".#.#.#\n...##.\n#....#\n..#...\n#.#..#\n####..\n"));
    }

    @Test void canCountLights() throws FileNotFoundException, IOException {
        LightGrid lightGrid = LightGrid.parse(new FileInputStream("test-input.txt"));
        assertTrue(lightGrid.getCount() == 15);
    }

    @Test void canIterateGrid() throws FileNotFoundException, IOException {
        LightGrid lightGrid = LightGrid.parse(new FileInputStream("test-input.txt"));

        assertTrue(lightGrid.getCount() == 15);

        lightGrid.iterate();
        assertTrue(lightGrid.getCount() == 11);

        lightGrid.iterate();
        assertTrue(lightGrid.getCount() == 8);

        lightGrid.iterate();
        assertTrue(lightGrid.getCount() == 4);

        lightGrid.iterate();
        assertTrue(lightGrid.getCount() == 4);
    }

    @Test void canIterateGridN() throws FileNotFoundException, IOException {
        LightGrid lightGrid = LightGrid.parse(new FileInputStream("test-input.txt"));

        assertTrue(lightGrid.getCount() == 15);

        for (int i=0; i<4; i++){
            lightGrid.iterate();
        }

        assertTrue(lightGrid.getCount() == 4);
    }

    @Test void canIterateGridCornerOverride() throws FileNotFoundException, IOException {
        LightGrid lightGrid = LightGrid.parse(new FileInputStream("test-input.txt"));

        lightGrid.lightCorners();
        assertTrue(lightGrid.getCount() == 17);

        for (int i=0; i<5; i++){
            lightGrid.iterate();
            lightGrid.lightCorners();
        }

        assertTrue(lightGrid.getCount() == 17);
    }
}
