/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day09;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import filelinesloader.FileLinesLoader;

public class App {

    static List<PathLeg> paths() {
        List<PathLeg> paths = new ArrayList<>();
        String[] lines = FileLinesLoader.getLines("input.txt");
        for (String line : lines) {
            PathLeg[] parsedPaths = PathLeg.parsePathLegString(line);
            paths.addAll(Arrays.asList(parsedPaths));
        }
        return paths;
    }

    static void part1() {
        List<PathLeg> paths = App.paths();
        PathFinder pathFinder = new PathFinder(paths.toArray(new PathLeg[] {}));
        System.out.println(String.format("Shortest Path: %d", pathFinder.shortestDistanceThroughAllNodes()));
    }

    static void part2() {
        List<PathLeg> paths = App.paths();
        PathFinder pathFinder = new PathFinder(paths.toArray(new PathLeg[] {}));
        System.out.println(String.format("Longest Path: %d", pathFinder.longestDistanceThroughAllNodes()));
    }

    public static void main(String[] args) {
        part1();
        part2();
    }

}
