/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day04;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class App {
    public static void main(String[] args) {
        part1();
        part2();
    }

    static void part1() {
        System.out.println(indexAtFiveZeros("iwrupvqb"));
    }

    static void part2() {
        System.out.println(indexAtSixZeros("iwrupvqb"));
    }

    static int indexAtFiveZeros(String key) {
        try {
            MessageDigest md = MessageDigest.getInstance("md5");
            for (int i = 0;; i++) {
                md.update(String.format("%s%d", key, i).getBytes());
                byte[] result = md.digest();

                StringBuilder sb = new StringBuilder();
                for (int j = 0; j < Math.min(result.length, 5); j++) {
                    sb.append(String.format("%02X", result[j]));
                }
                if (sb.toString().startsWith("00000")) {
                    return i;
                }
                md.reset();
            }
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }

        return 0;
    }

    static int indexAtSixZeros(String key) {
        try {
            MessageDigest md = MessageDigest.getInstance("md5");
            for (int i = 0;; i++) {
                md.update(String.format("%s%d", key, i).getBytes());
                byte[] result = md.digest();

                StringBuilder sb = new StringBuilder();
                for (int j = 0; j < Math.min(result.length, 6); j++) {
                    sb.append(String.format("%02X", result[j]));
                }
                if (sb.toString().startsWith("000000")) {
                    return i;
                }
                md.reset();
            }
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }

        return 0;
    }
}
