/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day20;

public class App {

    final static int targetPresents = 33100000;

    public static void main(String[] args) {
        part1();
        part2();
    }

    private static void part1() {
        ElfVisitor elfVisitor = new ElfVisitor(10);

        int houseNumber = 1;
        while(true){
            int presents = elfVisitor.countPresentsAtInfiniteVisits(houseNumber);
            if(presents>=targetPresents) {
                break;
            }
            houseNumber++;
        }

        System.out.println("Part1 House Number at Target: " + houseNumber);
    }

    private static void part2() {
        ElfVisitor elfVisitor = new ElfVisitor(11);

        int houseNumber = 1;
        while(true){
            int presents = elfVisitor.countPresentsAtFiniteVisits(houseNumber);
            if(presents>=targetPresents) {
                break;
            }
            houseNumber++;
        }

        System.out.println("Part2 House Number at Target: " + houseNumber);
    }
}
