/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day08;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import filelinesloader.FileLinesLoader;

class StringEscapeTest {

    @Test
    void canCountDecodedStringsDiff() {
        String[] lines = FileLinesLoader.getLines("test-1-input.txt");
        assertTrue(StringEscapeCount.decodedDiff(lines[0]) == 2);
        assertTrue(StringEscapeCount.decodedDiff(lines[1]) == 2);
        assertTrue(StringEscapeCount.decodedDiff(lines[2]) == 3);
        assertTrue(StringEscapeCount.decodedDiff(lines[3]) == 5);
        assertTrue(StringEscapeCount.decodedDiff(lines[4]) == 3);
    }

    @Test
    void canCountEncodedStringDiff() {
        String[] lines = FileLinesLoader.getLines("test-2-input.txt");
        assertTrue(StringEscapeCount.encodedDiff(lines[0]) == 4);
        assertTrue(StringEscapeCount.encodedDiff(lines[1]) == 4);
        assertTrue(StringEscapeCount.encodedDiff(lines[2]) == 6);
        assertTrue(StringEscapeCount.encodedDiff(lines[3]) == 5);
    }
}
