/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day13;

import filelinesloader.FileLinesLoader;

public class App {
    public static void main(String[] args) {
        part1();
        part2();
    }

    private static void part1() {
        String[] lines = FileLinesLoader.getLines("input.txt");
        Relationship[] relationships = new Relationship[lines.length];
        for (int i = 0; i < lines.length; i++) {
            relationships[i] = Relationship.parseString(lines[i]);
        }
        HappinessFinder hf = new HappinessFinder(relationships);
        System.out.println(String.format("Max Happiness: %d", hf.maxHappiness()));
    }

    private static void part2() {
        String[] lines = FileLinesLoader.getLines("input2.txt");
        Relationship[] relationships = new Relationship[lines.length];
        for (int i = 0; i < lines.length; i++) {
            relationships[i] = Relationship.parseString(lines[i]);
        }
        HappinessFinder hf = new HappinessFinder(relationships);
        System.out.println(String.format("Max Happiness with Me: %d", hf.maxHappiness()));
    }

}
