/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day20;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void canCountInfiniteVisits() {
        ElfVisitor elfVisitor = new ElfVisitor(10);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(1),10);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(2),30);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(3),40);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(4),70);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(5),60);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(6),120);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(7),80);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(8),150);
        assertEquals(elfVisitor.countPresentsAtInfiniteVisits(9),130);
    }
}
