/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day06;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.io.IOException;

public class App {
    public static void main(String[] args) {
        try {
            part1();
            part2();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    static void part1() throws IOException {
        List<Instruction> insts = Instruction.parseString(Files.readString(Paths.get("input.txt")));

        BinaryLightGrid grid = new BinaryLightGrid(1000, 1000);
        grid.executeInstructions(insts);

        System.out.println(String.format("Lights on: %d", grid.lightsOn()));
    }

    static void part2() throws IOException {
        List<Instruction> insts = Instruction.parseString(Files.readString(Paths.get("input.txt")));

        VariableLightGrid grid = new VariableLightGrid(1000, 1000);
        grid.executeInstructions(insts);

        System.out.println(String.format("Lights on: %d", grid.brightness()));
    }
}
