/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day11;

public class App {
    public static void main(String[] args) {
        String nextPassword = SantaPassword.nextPassword("hxbxwxba");
        System.out.println(String.format("Next password: %s", nextPassword));

        nextPassword = SantaPassword.nextPassword(nextPassword);
        System.out.println(String.format("Next password: %s", nextPassword));
    }
}
