/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day04;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void canFindIndexAtFiveZeros() {
        assertTrue(App.indexAtFiveZeros("abcdef") == 609043);
        assertTrue(App.indexAtFiveZeros("pqrstuv") == 1048970);
    }
}
