/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day14;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import filelinesloader.FileLinesLoader;

public class App {
    public static void main(String[] args) {
        Reindeer[] reindeer = getReindeer();

        part1(reindeer);
        part2(reindeer);
    }

    private static void part1(Reindeer[] reindeer) {
        List<RaceResult> results = new ArrayList<>();
        for (Reindeer r : reindeer) {
            results.add(new RaceResult(r.name, r.distance(2503)));
        }

        results.sort((a, b) -> {
            return b.score - a.score;
        });

        System.out.println(String.format("%s %d", results.get(0).name, results.get(0).score));
    }

    private static void part2(Reindeer[] reindeer) {
        Map<String, Integer> raceResults = new HashMap<>();
        for (int i = 1; i <= 2503; i++) {
            List<RaceResult> secondResults = new ArrayList<>();
            for (Reindeer r : reindeer) {
                secondResults.add(new RaceResult(r.name, r.distance(i)));
            }

            secondResults.sort((a, b) -> {
                return b.score - a.score;
            });

            int maxDistance = secondResults.get(0).score;

            for (Reindeer r : reindeer) {
                if (r.distance(i) == maxDistance) {
                    raceResults.put(r.name, raceResults.getOrDefault(r.name, 0) + 1);
                }
            }

        }

        List<RaceResult> raceResultsList = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : raceResults.entrySet()) {
            raceResultsList.add(new RaceResult(entry.getKey(), entry.getValue()));
        }

        raceResultsList.sort((a, b) -> {
            return b.score - a.score;
        });

        System.out.println(String.format("%s %d", raceResultsList.get(0).name, raceResultsList.get(0).score));
    }

    private static Reindeer[] getReindeer() {
        String[] lines = FileLinesLoader.getLines("input.txt");
        Reindeer[] reindeer = new Reindeer[lines.length];
        for (int i = 0; i < lines.length; i++) {
            reindeer[i] = Reindeer.parseString(lines[i]);
        }
        return reindeer;
    }
}

class RaceResult {
    String name;
    int score;

    RaceResult(String name, int score) {
        this.name = name;
        this.score = score;
    }
}
