/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void canGetPosition() {
        assertEquals(App.getPosition("(())"), 0);
        assertEquals(App.getPosition("()()"), 0);
        assertEquals(App.getPosition("((("), 3);
        assertEquals(App.getPosition("(()(()("), 3);
        assertEquals(App.getPosition("))((((("), 3);
        assertEquals(App.getPosition("())"), -1);
        assertEquals(App.getPosition("))("), -1);
        assertEquals(App.getPosition(")))"), -3);
        assertEquals(App.getPosition(")())())"), -3);
    }
}
