/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day18;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws FileNotFoundException, IOException {
        part1();
        part2();
    }

    private static void part1() throws IOException, FileNotFoundException {
        LightGrid lg = LightGrid.parse(new FileInputStream("input.txt"));

        for (int i=0; i<100; i++){
            lg.iterate();
        }

        System.out.println(String.format("Lights On: %d", lg.getCount()));
    }
    
    private static void part2() throws IOException, FileNotFoundException {
        LightGrid lg = LightGrid.parse(new FileInputStream("input.txt"));

        lg.lightCorners();
        for (int i=0; i<100; i++){
            lg.iterate();
            lg.lightCorners();
        }

        System.out.println(String.format("Lights On: %d", lg.getCount()));
    }
}
