/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day10;

public class App {
    public static void main(String[] args) {
        part1();
        part2();
    }

    private static void part1() {
        String input = "1321131112";
        for (int i = 0; i < 40; i++) {
            input = LookAndSay.lookAndSay(input);
        }
        System.out.println(String.format("Length: %d", input.length()));
    }

    private static void part2() {
        String input = "1321131112";
        for (int i = 0; i < 50; i++) {
            input = LookAndSay.lookAndSay(input);
        }
        System.out.println(String.format("Length: %d", input.length()));
    }
}
