/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day01;

import java.nio.file.Files;
import java.nio.file.Paths;

public class App {

    public static int getPosition(String ticks) {
        int count = 0;
        for (char c : ticks.toCharArray()) {
            switch (c) {
                case '(':
                    count++;
                    break;
                case ')':
                    count--;
                    break;
            }
        }
        return count;
    }

    public static void part1(String ticks) {
        int count = 0;
        for (char c : ticks.toCharArray()) {
            switch (c) {
                case '(':
                    count++;
                    break;
                case ')':
                    count--;
                    break;
            }
        }
        System.out.println(String.format("Position: %d", count));
    }

    public static void part2(String tickString) {
        int count = 0;
        char[] ticks = tickString.toCharArray();
        for (int i = 0; i < ticks.length; i++) {
            switch (ticks[i]) {
                case '(':
                    count++;
                    break;
                case ')':
                    count--;
                    break;
            }
            if (count == -1) {
                System.out.println(String.format("Tick Position: %d", i + 1));
                return;
            }
        }
    }

    public static void main(String[] args) {
        try {
            String ticks = new String(Files.readAllBytes(Paths.get("./input.txt")));
            part1(ticks);
            part2(ticks);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
