[package]
name = "part01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exit = "0.2.0"
float-ord = "0.3.2"
md5 = "0.7.0"
