/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day17;

import java.util.Set;

import filelinesloader.FileLinesLoader;

public class App {
    public static void main(String[] args) {
        String[] lines = FileLinesLoader.getLines("input.txt");
        Container[] containers = Container.parse(lines);
        Set<Set<Container>> combinations = ContainerCombinations.findCombinations(containers, 150);


        int minSize = Integer.MAX_VALUE;
        for (Set<Container> combination : combinations) {
            if (combination.size() < minSize) {
                minSize = combination.size();
            }
        }

        int minSizeCount = 0;
        for (Set<Container> combination : combinations) {
            if (combination.size() == minSize) {
                minSizeCount++;
            }
        }
        System.out.println(String.format("Combinations: (%s)", combinations.size()));
        System.out.println(String.format("Combinations at min size: (%s)", minSizeCount));
    }
}
